# Generated by Django 4.1 on 2022-08-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('ciudad_residencia', models.CharField(max_length=50)),
                ('linkedln', models.URLField()),
            ],
            options={
                'db_table': 'mentores',
            },
        ),
    ]
